# RT1W CI CONFIG
# 
# Stefan Wong 2020

dist: bionic
sudo: false
language: cpp

compiler: 
    - clang
    - gcc

matrix:
    include:
        os: linux
        addons:
            apt:
                sources:
                    ubuntu-toolchain-r-test
                packages:
                    - g++-6
        env:
            MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    eval "${MATRIX_EVAL}"

#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get -q update
#  - sudo apt-get -y install gcc-6.0


script:
    - make clean && make all
    - ./bin/test/test_ray
    - ./bin/test/test_sphere
    - ./bin/test/test_vec3
